# Generated by Django 5.0.1 on 2024-05-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
